services:
  backend:
    build: ./backend  # Path to backend Dockerfile
    ports:
      - "8000:8000"
    # For GPU support (if needed):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  frontend:
    build: ./frontend  # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    depends_on:
      - backend
