# Generated by Django 4.1.3 on 2022-12-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numRewievs',
            new_name='numReviews',
        ),
    ]
